# Generated by Django 5.1.4 on 2024-12-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizsession_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
